name: oliver_app
description: "La aplicación de los Oliveros."
publish_to: 'none'
version: 2.0.0+3

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  pdfx: ^2.5.0
  shared_preferences: ^2.2.2
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

# Configuración para el icono de la app
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icono.png"

flutter:
  uses-material-design: true

  assets:
    - assets/imagenes/l46_domingos/
    - assets/imagenes/l46_laborables/
    - assets/imagenes/l46_laborablesvc/
    - assets/imagenes/l46_sabados/
    - assets/imagenes/l52_domingos/
    - assets/imagenes/l52_laborables/
    - assets/imagenes/l52_sabados/
    - assets/imagenes/l72_domingos/
    - assets/imagenes/l72_laborables/
    - assets/imagenes/l72_sabados/
    - assets/imagenes/l74_domingos/
    - assets/imagenes/l74_laborables/
    - assets/imagenes/l74_sabados/
    - assets/imagenes/l76_domingos/
    - assets/imagenes/l76_laborables/
    - assets/imagenes/l76_sabados/
    - assets/imagenes/l77_agosto/
    - assets/imagenes/l77_laborables/
    - assets/imagenes/l78_domingos/
    - assets/imagenes/l78_laborables/
    - assets/imagenes/l78_sabados/
    - assets/imagenes/lx70_domingos/
    - assets/imagenes/lx70_laborables/
    - assets/imagenes/lx70_sabados/
    - assets/imagenes/m5_domingos/
    - assets/imagenes/m5_laborables/
    - assets/imagenes/m5_sabados/
    - assets/imagenes/m75_domingos/
    - assets/imagenes/m75_laborables/
    - assets/imagenes/m75_sabados/
    - assets/imagenes/sb1_domingos/
    - assets/imagenes/sb1_laborables/
    - assets/imagenes/sb1_sabados/
    - assets/imagenes/sb2_laborables/
    - assets/imagenes/sb2_sabados/
    - assets/imagenes/sb3_laborables/
    - assets/imagenes/sb3_sabados/
    - assets/imagenes/x43_laborables/
    - assets/imagenes/x43_sabados/
    - assets/imagenes/x79_domingos/
    - assets/imagenes/x79_laborables/
    - assets/imagenes/x79_sabados/
    - assets/imagenes/calendario_fiestas/
    - assets/imagenes/cuadro_vacaciones/
    - assets/imagenes/documentacion/
    - assets/pdfs/
    - assets/icono.png
